name: Run Tests

on:
  push:
    branches:
      - review

jobs:
  jest_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm run jest-test:detailed

  cypress_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Start application
        run: npm start &

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          baseUrl: ${{ secrets.BURGER_API_URL }}
          browser: chrome

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
