name: Run Tests

on:
  push:
    branches:
      - review

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm run start &

      - name: Wait for server to be ready
        run: |
          while ! nc -z localhost 4000; do   
            sleep 1
          done 

      - name: Run Jest tests
        run: npm run jest-test:detailed

      - name: Run Cypress tests
        run: npm run cypress-test:run

      - name: Upload Screenshots
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**/*